"""Initial migration

Revision ID: 0d8428bab60a
Revises: 494296564172
Create Date: 2025-06-25 17:57:16.353010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8428bab60a'
down_revision = '494296564172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('capsule_locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('capsule_locked_until')
        batch_op.drop_column('login_locked_until')

    # ### end Alembic commands ###
