"""Add capsule_otp_secret to TimeCapsule

Revision ID: 494296564172
Revises: a30aa7c4ac0f
Create Date: 2025-06-23 17:30:34.681355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494296564172'
down_revision = 'a30aa7c4ac0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capsule_otp_secret', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.drop_column('capsule_otp_secret')

    # ### end Alembic commands ###
