"""Add is_decrypted field to TimeCapsule

Revision ID: 5dc6e67364ce
Revises: 0d8428bab60a
Create Date: 2025-06-27 00:08:59.524107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc6e67364ce'
down_revision = '0d8428bab60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_decrypted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.drop_column('is_decrypted')

    # ### end Alembic commands ###
