"""Rename attempt_time to timestamp in OTPAttempt

Revision ID: 7ec955ebe6a3
Revises: e044c831c919
Create Date: 2025-07-05 16:59:13.829288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ec955ebe6a3'
down_revision = 'e044c831c919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('attempt_time')

    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['capsule_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('otp_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
