"""Added capsule_id and original_filename

Revision ID: 9b9ed230d239
Revises: 5dc6e67364ce
Create Date: 2025-07-04 19:47:50.948211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9ed230d239'
down_revision = '5dc6e67364ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('time_capsules_capsule_id_key'), type_='unique')
        batch_op.drop_column('capsule_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_capsules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capsule_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('time_capsules_capsule_id_key'), ['capsule_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
